# -*- coding: utf-8 -*-
"""EmailSender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWQezKU_x0gFfM8haBjUWcScGjHPRaCv
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

def send_passes_via_email(email, pass_filename):
    # Set up the email server and login credentials
    smtp_server = 'your_smtp_server.com'
    smtp_port = 587  # Adjust the port as needed
    smtp_username = 'your_email@example.com'
    smtp_password = 'your_email_password'

    # Set up the sender and recipient emails
    sender_email = 'jaywantadhau16003@gmail.com'
    recipient_email = email

    # Create the email message
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = 'Your Event Pass'

    # Attach the pass to the email
    with open(pass_filename, "rb") as file:
        attach = MIMEApplication(file.read(), _subtype="png")
        attach.add_header('Content-Disposition', 'attachment', filename=os.path.basename(pass_filename))
        msg.attach(attach)

    # Connect to the SMTP server and send the email
    with smtplib.SMTP(smtp_server, smtp_port) as server:
        server.starttls()
        server.login(smtp_username, smtp_password)
        server.sendmail(sender_email, recipient_email, msg.as_string())

def send_passes_to_emails(email_list):
    output_folder = "passes_output"

    # Loop through each email and send the corresponding pass
    for pass_id, email in enumerate(email_list, start=1):
        pass_filename = os.path.join(output_folder, f"Anahita Yadav.png")  # Adjust the filename accordingly
        send_passes_via_email(email, pass_filename)
        print(f"Pass sent to {email}")

if __name__ == "__main__":
    # Replace this list with the actual emails you want to send passes to
    recipient_emails = ['example1@example.com', 'example2@example.com']

    # Call the function to send passes to the specified emails
    send_passes_to_emails(recipient_emails)