# -*- coding: utf-8 -*-
"""PassMaker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvlSygtuKgyjrYq7itHusGuF-McKR7Mm
"""

import os
from PIL import Image

# Function to create the passes
def create_passes():
    template_path = "Animethon-org.png"  # Replace with the path to your Canva template
    output_folder = "passes_output"  # Replace with the name of your output folder

    # Ensure the output folder exists, create it if necessary
    os.makedirs(output_folder, exist_ok=True)

    # Replace with the filenames of your 230 QR code images
    qr_code_filenames = [
  "Anahita Yadav.png"
];
    # Loop through each QR code and generate the pass
    for pass_id, qr_code_filename in enumerate(qr_code_filenames, start=1):
        # Load the template image
        template_image = Image.open(template_path)

        # Load the QR code image
        qr_code_image = Image.open(qr_code_filename)

        # Resize the QR code to fit the designated space on the template
        qr_code_image = qr_code_image.resize((340, 340))

        # Replace x and y with the coordinates to paste the QR code on the template
        x, y = 1600, 60

        # Paste the QR code onto the template
        template_image.paste(qr_code_image, (x, y))

        # Save the final pass with the QR code
        pass_filename = os.path.join(output_folder, f"{qr_code_filenames[pass_id-1]}")
        template_image.save(pass_filename)

# Call the function to create the passes
create_passes()